definitions:
  request.AddressPatchReq:
    properties:
      address_id:
        type: integer
      address_line_1:
        type: string
      address_line_2:
        type: string
      city:
        type: string
      country:
        type: string
      house:
        type: string
      is_default:
        type: boolean
      pin_code:
        type: string
      state:
        type: string
    type: object
  request.Block:
    properties:
      user_id:
        type: integer
    required:
    - user_id
    type: object
  request.CreateCoupon:
    properties:
      code:
        type: string
      discount_max_amount:
        type: number
      discount_percent:
        type: number
      min_order_value:
        type: number
      valid_till:
        type: string
    type: object
  request.LoginData:
    properties:
      Password:
        maxLength: 30
        minLength: 3
        type: string
      email:
        description: Phone    string `json:"phone" binding:"omitempty,min=10,max=10"`
        type: string
      user_name:
        maxLength: 15
        minLength: 3
        type: string
    required:
    - Password
    type: object
  request.OTPVerify:
    properties:
      otp:
        maxLength: 8
        minLength: 4
        type: string
      user_id:
        type: integer
    required:
    - otp
    - user_id
    type: object
  request.SignupUserData:
    properties:
      age:
        type: integer
      email:
        type: string
      first_name:
        maxLength: 50
        minLength: 2
        type: string
      last_name:
        maxLength: 50
        minLength: 1
        type: string
      password:
        type: string
      phone:
        maxLength: 10
        minLength: 10
        type: string
      user_name:
        maxLength: 15
        minLength: 3
        type: string
    required:
    - age
    - email
    - first_name
    - last_name
    - password
    - phone
    - user_name
    type: object
  response.Response:
    properties:
      data: {}
      errors: {}
      message:
        type: string
      status_code:
        type: integer
    type: object
info:
  contact: {}
paths:
  /admin/:
    get:
      description: Welcome to Admin Home
      operationId: AdminHome
      responses:
        "200":
          description: Successfully logged in
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admin Home
      tags:
      - Admin
  /admin/coupons:
    post:
      description: List all coupons
      parameters:
      - description: Number of users to fetch per page
        in: query
        name: count
        type: integer
      - description: Page number
        in: query
        name: page_number
        type: integer
      responses:
        "200":
          description: List of coupons
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: invalid inputs
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: internal serever error
          schema:
            $ref: '#/definitions/response.Response'
      summary: List all coupons
      tags:
      - Coupon
  /admin/login:
    post:
      consumes:
      - application/json
      description: Login to Admin account
      operationId: AdminLogin
      parameters:
      - description: inputs
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.LoginData'
      responses:
        "200":
          description: Successfully logged in
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Failed to login
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Generate JWT failure
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admin Login
      tags:
      - Admin
  /admin/signup:
    post:
      consumes:
      - application/json
      description: Create new Admin account
      operationId: AdminSignUp
      parameters:
      - description: inputs
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.SignupUserData'
      responses:
        "200":
          description: Admin account created successfully
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Failed to create Admin account
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admin SignUp
      tags:
      - Admin
  /admin/users/block:
    patch:
      consumes:
      - application/json
      description: Block users in admin side
      operationId: BlockUser
      parameters:
      - description: inputs
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.Block'
      responses:
        "200":
          description: Successfully changed user block_status
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Failed to change user block_status
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admin Block Users
      tags:
      - Admin
  /login:
    post:
      consumes:
      - application/json
      description: Login to user account
      operationId: User login
      parameters:
      - description: inputs
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.LoginData'
      responses:
        "200":
          description: OTP send to your mobile number!
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Failed to login
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Generate JWT failure
          schema:
            $ref: '#/definitions/response.Response'
      summary: User login
      tags:
      - User
  /login/otp-verify:
    post:
      consumes:
      - application/json
      description: OTP Verification to user account
      operationId: User OTP Verification
      parameters:
      - description: inputs
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.OTPVerify'
      responses:
        "200":
          description: Successfully logged in
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Missing or Invalid entry
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Failed to login
          schema:
            $ref: '#/definitions/response.Response'
      summary: User OTP Verification
      tags:
      - User
  /profile/address:
    put:
      description: user can update a address
      operationId: DeleteAddress
      parameters:
      - description: Input Field
        in: body
        name: inputs
        required: true
        schema:
          $ref: '#/definitions/request.AddressPatchReq'
      responses:
        "200":
          description: Address deleted successfuly
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Something went wrong!
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: api for update user address
      tags:
      - Update Order
  /signup:
    post:
      consumes:
      - application/json
      description: Create new user account
      operationId: User Signup
      parameters:
      - description: inputs
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.SignupUserData'
      responses:
        "200":
          description: Successfully logged in
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Missing or Invalid entry
          schema:
            $ref: '#/definitions/response.Response'
      summary: User Signup
      tags:
      - User
  /users:
    get:
      description: Get a paginated list of users.
      parameters:
      - description: Number of users to fetch per page
        in: query
        name: count
        type: integer
      - description: Page number
        in: query
        name: page_number
        type: integer
      responses:
        "200":
          description: List user successful
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Missing or invalid inputs
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Failed to get all users
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get a list of users
      tags:
      - Users
swagger: "2.0"
